name: PacketLink
version: 0.0.7
api: [3.0.0, 3.0.0-ALPHA5]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
author: MineRealm
website: https://github.com/MineRealm/PacketLink
load: STARTUP
main: MineRealm\PacketLink\PacketLink