name: PacketLink
version: 1.6.0-beta
api: [3.0.0, 3.0.0-ALPHA4]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
author: MineRealm
website: https://github.com/MineRealm/PacketLink
load: STARTUP
main: MineRealm\PacketLink\PacketLink